### ISSUE TITLE
有时候不能commit

### ISSUE THREAD

**Issue by lhuanran** [CoderSerio/jit#1]
有时候commit会报错，为什么呢？

**Comment by CoderSerio** [comment]
你的描述还不够详细，我们只能推测可能的原因：
1. 没有执行init，add等前置命令
2. 没有给予管理员权限

**Comment by CoderSerio** [comment]
![image](https://user-images.githubusercontent.com/79406469/220718837-8e0d1b22-6f74-4629-b5c2-ec0367cd603a.png)
像上面这样抱错时，可以尝试加上sudo赋予管理员权限
